<?php

class SettingsWriteModule extends BaseWriteModule {

	function write() {
		
		if (isset(Request::$post['id'][0])) {
			if (isset(Request::$post['name'][0]) && Request::$post['name'][0]) {
				$this->_new();
			}
		}

		$names = isset(Request::$post['name']) ? Request::$post['name'] : array();

		foreach ($names as $key => $name) {
			$id = (int) Request::$post['id'][$key];
			$name = Request::$post['name'][$key];
			$value = Request::$post['value'][$key];
			$comment = Request::$post['comment'][$key];
			$query = 'INSERT INTO `settings` SET
			`id` = ' . $id . ',
			`name`=' . Database::escape($name) . ',
			`comment`=' . Database::escape($comment) . ',
			`value`=' . Database::escape($value) . '
				ON DUPLICATE KEY UPDATE
			`name`=' . Database::escape($name) . ',
			`comment`=' . Database::escape($comment) . ',
			`value`=' . Database::escape($value);
			Database::query($query);
		}
		$this->saveSettings();
	}

	function _new() {
		$name = Request::$post['name'][0];
		$value = Request::$post['value'][0];
		$comment = Request::$post['comment'][$key];
		$query = 'INSERT INTO `settings` SET
			`name`=' . Database::escape($name) . ',
			`comment`=' . Database::escape($comment) . ',
			`value`=' . Database::escape($value);
		Database::query($query);
	}

	function saveSettings() {
		require_once ($filename = dirname(Config::need('xslt_files_path')) . '/localconfig.php');
		global $local_config;
		$query = 'SELECT * FROM `settings`';
		$arr = Database::sql2array($query);
		$local_config['-----------------'] = '-----------------';
		foreach ($arr as $setting) {
			$local_config[$setting['name']] = $setting['value'];
		}
		$s = var_export($local_config, true);
		file_put_contents($filename, '<?php $local_config = ' . $s . ";\n" . '//some settings generated by setting module');
	}

}